# Generated by Django 6.0.5 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneddataset',
            name='ai_insights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='before_after',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='cell_annotations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='cleaning_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='cleaning_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='health_report',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='quality_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='raw_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='raw_snapshot',
            field=models.JSONField(default=list),
        ),
    ]
