# Generated by Django 6.0.5 on 2026-05-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cleaneddataset_ai_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneddataset',
            name='parquet_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cleaneddataset',
            name='rows',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
