# Generated by Django 6.0.4 on 2026-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_csvdataset_datapoint_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdataset',
            name='imported_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvdataset',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvdataset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='pending', max_length=15),
        ),
    ]
