# Generated by Django 6.0.4 on 2026-05-19 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_csvdataset_imported_count_csvdataset_skipped_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('cleaning_log', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SavedChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('scatter', 'Scatter')], max_length=20)),
                ('x_axis', models.CharField(max_length=255)),
                ('y_axis', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_charts', to='app.cleaneddataset')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cleaneddataset',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_dataset', to='app.uploadedfile'),
        ),
    ]
