# Generated by Django 6.0.4 on 2026-05-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_teammembership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneddataset',
            name='all_sheets_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
